import{i as s,a as y,S as f}from"./assets/vendor-DjDxajEQ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const b="45506482-0746cd613ccb32219c9653431",L="https://pixabay.com/api/";async function h(e,o=1,a=15){if(!e.trim())return s.error({message:"Please enter a search query!",position:"topRight"}),[];const i={params:{key:b,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:a,page:o}};try{document.querySelector(".loader").classList.remove("hidden");const r=(await y.get(L,i)).data;return r.hits.length===0&&s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),r}catch(t){return console.log(t),s.error({message:"An error occurred while fetching images. Please try again later.",position:"topRight"}),[]}finally{document.querySelector(".loader").classList.add("hidden")}}let g;const v=e=>` <li class="gallery-card">
      <a href="${e.largeImageURL}" class="gallery-item">
        <img class="gallery-img" src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        <div class="info">
          <p class="info-item"><b>Likes:</b> ${e.likes}</p>
          <p class="info-item"><b>Views:</b> ${e.views}</p>
          <p class="info-item"><b>Comments:</b> ${e.comments}</p>
          <p class="info-item"><b>Downloads:</b> ${e.downloads}</p>
        </div>
      </a>
    </li>`;function m(e){const o=document.querySelector(".gallery"),a=e.map(i=>v(i)).join("");o.insertAdjacentHTML("beforeend",a),g=new f(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}),g.refresh()}const w=document.querySelector(".submit-form"),P=document.querySelector(".search-input"),q=document.querySelector(".gallery"),c=document.querySelector(".load-btn");let n=1;const u=15;let l="",p=0;function R(){q.innerHTML=""}w.addEventListener("submit",async e=>{if(e.preventDefault(),l=P.value.trim(),!l){s.error({message:"Please enter a search query!",position:"topRight"});return}R(),n=1,c.classList.add("hidden-btn");try{const{hits:o,totalHits:a}=await h(l,n,u);o.length>0?(m(o),p=Math.ceil(a/u),n<p?c.classList.remove("hidden-btn"):s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):c.classList.add("hidden-btn")}catch{s.error({message:"An error occurred. Please try again later.",position:"topRight"})}});c.addEventListener("click",async()=>{n+=1;try{const{hits:e}=await h(l,n,u);if(e.length>0){m(e);const{height:o}=document.querySelector(".gallery-card").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),n>=p&&(c.classList.add("hidden-btn"),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}else s.info({message:"No more images to load",position:"topRight"})}catch{s.error({message:"An error occurred while loading more images. Please try again later.",position:"topRight"})}});
//# sourceMappingURL=index.js.map
